### ISSUE TITLE
Hi, some link is unaccessible

### ISSUE THREAD

**Issue by hanquansanren** [FelixHertlein/inv3d-generator#1]
In the README file, the HDR environment maps link is 404 NOT found.
 [full dataset](http://www.hdrdb.com/indoor/)

Can you provide an extra link for the full HDR dataset?

Best Wishes

**Comment by FelixHertlein** [comment]
Unfortunately, I cannot provide the dataset itself since I do not have the rights on it.

To get access to the dataset you can contact the original author as described here:
[https://web.archive.org/web/20220327063301/http://indoor.hdrdb.com/](https://web.archive.org/web/20220327063301/http://indoor.hdrdb.com/)

Hope this helps.

**Comment by hanquansanren** [comment]
Many thanks for your kind responses. I would try to contact the original author. ٩('ω')و
